# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
playsound minecraft:item.bucket.fill block @a[distance=..16] ~ ~ ~ 1
tag @s remove c_wp_cauldron_full