# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.wp_cauldron.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'wp_cauldron', 'function_path': 'animated_java:wp_cauldron/remove/this'}
execute at @s run playsound minecraft:block.iron.break block @a[distance=..16] ~ ~ ~ 1 1
execute at @s run summon item ~ ~ ~ {Motion:[0.0,0.3,0.0],Item:{id:"minecraft:witch_spawn_egg",count:1,components:{"minecraft:entity_data":{id:"minecraft:marker",Tags:["c_wp_cauldron_spawn"]},"minecraft:item_model":"witchpack:cauldron","minecraft:item_name":"Witch's Cauldron","minecraft:rarity":"uncommon"}}}
execute on passengers run kill @s
kill @s