# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.wp_mandrake.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'wp_mandrake', 'function_path': 'animated_java:wp_mandrake/variants/default/apply'}
execute on passengers if entity @s[tag=aj.wp_mandrake.bone.leafw] run function animated_java:wp_mandrake/variants/default/zzz/apply_to_bone_leafw
execute on passengers if entity @s[tag=aj.wp_mandrake.bone.leafs] run function animated_java:wp_mandrake/variants/default/zzz/apply_to_bone_leafs
execute on passengers if entity @s[tag=aj.wp_mandrake.bone.leafn] run function animated_java:wp_mandrake/variants/default/zzz/apply_to_bone_leafn
execute on passengers if entity @s[tag=aj.wp_mandrake.bone.leafe] run function animated_java:wp_mandrake/variants/default/zzz/apply_to_bone_leafe
execute on passengers if entity @s[tag=aj.wp_mandrake.bone.neck] run function animated_java:wp_mandrake/variants/default/zzz/apply_to_bone_neck
execute on passengers if entity @s[tag=aj.wp_mandrake.bone.body] run function animated_java:wp_mandrake/variants/default/zzz/apply_to_bone_body
execute on passengers if entity @s[tag=aj.wp_mandrake.bone.left] run function animated_java:wp_mandrake/variants/default/zzz/apply_to_bone_left
execute on passengers if entity @s[tag=aj.wp_mandrake.bone.right] run function animated_java:wp_mandrake/variants/default/zzz/apply_to_bone_right
return 1