# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.wp_mandrake.node.leafw] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_leafw set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.wp_mandrake.node.leafs] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_leafs set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.wp_mandrake.node.leafn] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_leafn set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.wp_mandrake.node.leafe] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_leafe set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.wp_mandrake.node.neck] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_neck set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.wp_mandrake.node.body] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_body set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.wp_mandrake.node.left] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_left set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.wp_mandrake.node.right] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_right set from storage aj:uuid main.out