# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute store result score @s aj.id run scoreboard players add aj.last_id aj.id 1
# Data Manager: Initalize per-entity storage
function animated_java:global/gu/get_entity_uuid_string
data modify storage animated_java:temp args.uuid set from storage animated_java:gu out
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
function animated_java:global/data_manager/create_entry with storage animated_java:temp args
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Read
function animated_java:global/data_manager/read with storage animated_java:temp args
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.root_uuid set from storage animated_java:gu out
data modify storage animated_java:temp entry.data.blueprint_id set value "aj:wp_mandrake"
data modify storage animated_java:temp entry.data.rig_hash set value "7cba961f57ff28cfe5fb3730de67e5710c249a884c74521824cc70f149b3585a"
tp @s ~ ~ ~ ~ ~
execute on passengers if entity @s[tag=aj.wp_mandrake.node.leafw] run function aj:wp_mandrake/zzz/summon/as_node/leafw
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.leafw set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.wp_mandrake.node.leafs] run function aj:wp_mandrake/zzz/summon/as_node/leafs
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.leafs set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.wp_mandrake.node.leafn] run function aj:wp_mandrake/zzz/summon/as_node/leafn
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.leafn set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.wp_mandrake.node.leafe] run function aj:wp_mandrake/zzz/summon/as_node/leafe
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.leafe set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.wp_mandrake.node.neck] run function aj:wp_mandrake/zzz/summon/as_node/neck
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.neck set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.wp_mandrake.node.body] run function aj:wp_mandrake/zzz/summon/as_node/body
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.body set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.wp_mandrake.node.left] run function aj:wp_mandrake/zzz/summon/as_node/left
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.left set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.wp_mandrake.node.right] run function aj:wp_mandrake/zzz/summon/as_node/right
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.right set from storage animated_java:gu out
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
function aj:wp_mandrake/zzz/set_default_pose
execute if data storage animated_java:temp args.variant run function aj:wp_mandrake/zzz/summon/variant_arg/process with storage animated_java:temp args
execute if score #success aj.i matches 0 run return fail
execute if data storage animated_java:temp args.animation run function aj:wp_mandrake/zzz/summon/animation_arg/process with storage animated_java:temp args
execute if score #success aj.i matches 0 run return fail
execute on passengers run rotate @s ~ ~
data modify entity @s teleport_duration set value 1
execute on passengers run data modify entity @s teleport_duration set value 1
execute at @s run function aj:wp_mandrake/zzz/summon/on_summon/rig
tag @s remove aj.new
execute on passengers run tag @s remove aj.new