# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(leafw) { transformation: [-1f,0f,0f,0f,0f,1f,0f,0.1438f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(leafs) { transformation: [-1f,0f,0f,0f,0f,1f,0f,0.1438f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(leafn) { transformation: [-1f,0f,0f,0f,0f,1f,0f,0.1438f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(leafe) { transformation: [-1f,0f,0f,0f,0f,1f,0f,0.1438f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(neck) { transformation: [-1f,0f,0f,0f,0f,1f,0f,0.0187f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(body) { transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.2312f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(left) { transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.2312f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(right) { transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.2312f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }