# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:wp_mandrake/animations/idle/stop
execute store result score @s c_wp_e_attack_cd run random value 300..600