# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.wp_cauldron.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'wp_cauldron', 'function_path': 'animated_java:wp_cauldron/animations/water_full/apply_frame'}
data remove storage aj:temp args
$execute store result storage aj:temp args.frame int 1 run scoreboard players set @s aj.water_full.frame $(frame)
execute at @s run function animated_java:wp_cauldron/animations/water_full/zzz/apply_frame with storage aj:temp args