# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.wp_cauldron.root] run return 0
execute on passengers if entity @s[tag=aj.wp_cauldron.data] unless data entity @s {data:{rigHash: '2b6d91434ad028c3a9c7bd0acef18907920eae73b5c6aad9354f1a6ca29fd965'}} on vehicle run function animated_java:wp_cauldron/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1