# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.wp_cauldron.root] run return 0
execute unless score @s aj.is_rig_loaded matches 1 run function #animated_java:global/root/on_load
execute if entity @s[tag=aj.wp_cauldron.animation.attacked.playing] run function animated_java:wp_cauldron/animations/attacked/zzz/on_tick
execute if entity @s[tag=aj.wp_cauldron.animation.water_empty.playing] run function animated_java:wp_cauldron/animations/water_empty/zzz/on_tick
execute if entity @s[tag=aj.wp_cauldron.animation.water_full.playing] run function animated_java:wp_cauldron/animations/water_full/zzz/on_tick
execute at @s on passengers run rotate @s ~ ~