# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$kill $(leafw)
$kill $(leafs)
$kill $(leafn)
$kill $(leafe)
$kill $(neck)
$kill $(body)
$kill $(left)
$kill $(right)