# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(leafw) {transformation: [-0.9997f,0.0262f,0f,0f,0.0262f,0.9997f,0f,0.1438f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leafs) {transformation: [-1f,0f,0f,0f,0f,0.9997f,-0.0262f,0.1438f,0f,-0.0262f,-0.9997f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leafn) {transformation: [-1f,0f,0f,0f,0f,0.9997f,0.0262f,0.1438f,0f,0.0262f,-0.9997f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leafe) {transformation: [-0.9997f,-0.0262f,0f,0f,-0.0262f,0.9997f,0f,0.1438f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}