# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(leafw) {transformation: [-0.9659f,-0.2588f,0f,0f,-0.25f,0.933f,-0.2588f,0.1395f,0.067f,-0.25f,-0.9659f,-0.0324f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leafs) {transformation: [-1f,0f,0f,0f,0f,0.9914f,0.1305f,0.1395f,0f,0.1305f,-0.9914f,-0.0324f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leafn) {transformation: [-1f,0f,0f,0f,0f,0.866f,-0.5f,0.1395f,0f,-0.5f,-0.866f,-0.0324f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leafe) {transformation: [-0.9659f,0.2588f,0f,0f,0.25f,0.933f,-0.2588f,0.1395f,-0.067f,-0.25f,-0.9659f,-0.0324f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck) {transformation: [-1f,0f,0f,0f,0f,0.9659f,-0.2588f,0.0187f,0f,-0.2588f,-0.9659f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
execute unless entity @s[tag=aj.transforms_only] at @s run function aj:wp_mandrake/animations/scream/zzz/frames/3_root_function