# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(cauldron) { transformation: [-1f,0f,0f,0f,0f,1f,0f,0f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(water) { transformation: [-1f,0f,0f,0.5f,0f,1f,0f,-0.5f,0f,0f,-1f,0.5f,0f,0f,0f,1f], start_interpolation: 0 }