# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Read
function animated_java:global/data_manager/read with storage animated_java:temp args
execute if score @s aj.attacked.frame matches 5.. run scoreboard players set @s aj.attacked.frame 1
data remove storage animated_java:temp args
execute store result storage animated_java:temp args.frame int 1 run scoreboard players get @s aj.attacked.frame
execute at @s run function aj:wp_cauldron/animations/attacked/zzz/apply_frame with storage animated_java:temp args
scoreboard players add @s aj.attacked.frame 1