# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute as $(leafw) run function aj:wp_mandrake/variants/default/zzz/apply_to_node_leafw
$execute as $(leafs) run function aj:wp_mandrake/variants/default/zzz/apply_to_node_leafs
$execute as $(leafn) run function aj:wp_mandrake/variants/default/zzz/apply_to_node_leafn
$execute as $(leafe) run function aj:wp_mandrake/variants/default/zzz/apply_to_node_leafe
$execute as $(neck) run function aj:wp_mandrake/variants/default/zzz/apply_to_node_neck
$execute as $(body) run function aj:wp_mandrake/variants/default/zzz/apply_to_node_body
$execute as $(left) run function aj:wp_mandrake/variants/default/zzz/apply_to_node_left
$execute as $(right) run function aj:wp_mandrake/variants/default/zzz/apply_to_node_right