# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:wp_mandrake/animations/walk/stop
function animated_java:wp_mandrake/animations/idle/stop
function animated_java:wp_mandrake/animations/scream/stop