# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage aj:wp_mandrake rig_hash set value '7cba961f57ff28cfe5fb3730de67e5710c249a884c74521824cc70f149b3585a'
scoreboard objectives add aj.scream.frame dummy
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.walk.frame dummy
scoreboard objectives add aj.death.frame dummy
scoreboard objectives add aj.spawn.frame dummy