# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage aj:wp_cauldron rig_hash set value 'ca9d2ca03281c1ce4b0f63382cdc237489413c5886bd8038c16b393c1e45df58'
scoreboard objectives add aj.attacked.frame dummy
scoreboard objectives add aj.water_empty.frame dummy
scoreboard objectives add aj.water_full.frame dummy