# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives add aj.attacked.frame dummy
scoreboard objectives add aj.water_empty.frame dummy
scoreboard objectives add aj.water_full.frame dummy