# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.wp_mandrake.root] run return 0
execute on passengers if entity @s[tag=aj.wp_mandrake.data] unless data entity @s {data:{rigHash: 'd2025c89ae5435dd00b618f1daebfb74e0dab10268e6e3c31944fab0bf2463bd'}} on vehicle run function animated_java:wp_mandrake/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1