# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.wp_mandrake.root] run return 0
execute unless score @s aj.is_rig_loaded matches 1 run function #animated_java:global/root/on_load
execute if entity @s[tag=aj.wp_mandrake.animation.scream.playing] run function animated_java:wp_mandrake/animations/scream/zzz/on_tick
execute if entity @s[tag=aj.wp_mandrake.animation.idle.playing] run function animated_java:wp_mandrake/animations/idle/zzz/on_tick
execute if entity @s[tag=aj.wp_mandrake.animation.walk.playing] run function animated_java:wp_mandrake/animations/walk/zzz/on_tick
execute if entity @s[tag=aj.wp_mandrake.animation.death.playing] run function animated_java:wp_mandrake/animations/death/zzz/on_tick
execute if entity @s[tag=aj.wp_mandrake.animation.spawn.playing] run function animated_java:wp_mandrake/animations/spawn/zzz/on_tick
execute at @s on passengers run rotate @s ~ ~
execute if entity @s[tag=!aj.wp_mandrake.animation.death.playing,tag=!aj.wp_mandrake.animation.spawn.playing] run function witchpack:mobs/mandrake_model