# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.wp_cauldron.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'wp_cauldron', 'function_path': 'animated_java:wp_cauldron/animations/pause_all'}
tag @s remove aj.wp_cauldron.animation.attacked.playing
tag @s remove aj.wp_cauldron.animation.water_empty.playing
tag @s remove aj.wp_cauldron.animation.water_full.playing