# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(water) {transformation: [-1f,0f,0f,0.5f,0f,1f,0f,0.375f,0f,0f,-1f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
execute unless entity @s[tag=aj.transforms_only] at @s run function aj:wp_cauldron/animations/water_empty/zzz/frames/0_root_function