# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if entity @s[tag=aj.wp_cauldron.animation.attacked.playing] run function aj:wp_cauldron/animations/attacked/zzz/on_tick
execute if entity @s[tag=aj.wp_cauldron.animation.water_empty.playing] run function aj:wp_cauldron/animations/water_empty/zzz/on_tick
execute if entity @s[tag=aj.wp_cauldron.animation.water_full.playing] run function aj:wp_cauldron/animations/water_full/zzz/on_tick