# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.wp_mandrake.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'wp_mandrake', 'function_path': 'animated_java:wp_mandrake/animations/scream/next_frame'}
execute if score @s aj.scream.frame matches 11.. run scoreboard players set @s aj.scream.frame 1
data remove storage aj:temp args
execute store result storage aj:temp args.frame int 1 run scoreboard players get @s aj.scream.frame
execute at @s run function animated_java:wp_mandrake/animations/scream/zzz/apply_frame with storage aj:temp args
scoreboard players add @s aj.scream.frame 1