# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(leafw) {transformation: [-0.9659f,0f,0.2588f,0f,0f,1f,0f,0.2791f,-0.2588f,0f,-0.9659f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leafs) {transformation: [-0.9659f,0f,0.2588f,0f,0f,1f,0f,0.2791f,-0.2588f,0f,-0.9659f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leafn) {transformation: [-0.9659f,0f,0.2588f,0f,0f,1f,0f,0.2791f,-0.2588f,0f,-0.9659f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leafe) {transformation: [-0.9659f,0f,0.2588f,0f,0f,1f,0f,0.2791f,-0.2588f,0f,-0.9659f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck) {transformation: [-0.9659f,0f,0.2588f,0f,0f,1f,0f,0.1541f,-0.2588f,0f,-0.9659f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [-0.9659f,0f,0.2588f,0f,0f,1f,0f,-0.0959f,-0.2588f,0f,-0.9659f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.0334f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.0691f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}