# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(leafw) {transformation: [-0.9962f,0f,0.0872f,0f,0f,1f,0f,0.3513f,-0.0872f,0f,-0.9962f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leafs) {transformation: [-0.9962f,0f,0.0872f,0f,0f,1f,0f,0.3513f,-0.0872f,0f,-0.9962f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leafn) {transformation: [-0.9962f,0f,0.0872f,0f,0f,1f,0f,0.3513f,-0.0872f,0f,-0.9962f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leafe) {transformation: [-0.9962f,0f,0.0872f,0f,0f,1f,0f,0.3513f,-0.0872f,0f,-0.9962f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck) {transformation: [-0.9962f,0f,0.0872f,0f,0f,1f,0f,0.2263f,-0.0872f,0f,-0.9962f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [-0.9962f,0f,0.0872f,0f,0f,1f,0f,-0.0237f,-0.0872f,0f,-0.9962f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0.0298f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0.012f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
execute unless entity @s[tag=aj.transforms_only] at @s run function aj:wp_mandrake/animations/spawn/zzz/frames/4_root_function