# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(leafw) {transformation: [-0.9659f,0f,-0.2588f,0f,0f,1f,0f,0.4956f,0.2588f,0f,-0.9659f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leafs) {transformation: [-0.9659f,0f,-0.2588f,0f,0f,1f,0f,0.4956f,0.2588f,0f,-0.9659f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leafn) {transformation: [-0.9659f,0f,-0.2588f,0f,0f,1f,0f,0.4956f,0.2588f,0f,-0.9659f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leafe) {transformation: [-0.9659f,0f,-0.2588f,0f,0f,1f,0f,0.4956f,0.2588f,0f,-0.9659f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck) {transformation: [-0.9659f,0f,-0.2588f,0f,0f,1f,0f,0.3706f,0.2588f,0f,-0.9659f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [-0.9659f,0f,-0.2588f,0f,0f,1f,0f,0.1206f,0.2588f,0f,-0.9659f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0.1564f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0.1742f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
execute unless entity @s[tag=aj.transforms_only] at @s run function aj:wp_mandrake/animations/spawn/zzz/frames/6_root_function