# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(leafw) {transformation: [-0.9808f,0f,-0.1951f,0f,0f,1f,0f,0.5678f,0.1951f,0f,-0.9808f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leafs) {transformation: [-0.9808f,0f,-0.1951f,0f,0f,1f,0f,0.5678f,0.1951f,0f,-0.9808f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leafn) {transformation: [-0.9808f,0f,-0.1951f,0f,0f,1f,0f,0.5678f,0.1951f,0f,-0.9808f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leafe) {transformation: [-0.9808f,0f,-0.1951f,0f,0f,1f,0f,0.5678f,0.1951f,0f,-0.9808f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck) {transformation: [-0.9808f,0f,-0.1951f,0f,0f,1f,0f,0.4428f,0.1951f,0f,-0.9808f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [-0.9808f,0f,-0.1951f,0f,0f,1f,0f,0.1928f,0.1951f,0f,-0.9808f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0.2197f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0.2553f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}