# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(leafw) {transformation: [-0.9979f,0f,-0.0654f,0f,0f,1f,0f,0.7122f,0.0654f,0f,-0.9979f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leafs) {transformation: [-0.9979f,0f,-0.0654f,0f,0f,1f,0f,0.7122f,0.0654f,0f,-0.9979f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leafn) {transformation: [-0.9979f,0f,-0.0654f,0f,0f,1f,0f,0.7122f,0.0654f,0f,-0.9979f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(leafe) {transformation: [-0.9979f,0f,-0.0654f,0f,0f,1f,0f,0.7122f,0.0654f,0f,-0.9979f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(neck) {transformation: [-0.9979f,0f,-0.0654f,0f,0f,1f,0f,0.5872f,0.0654f,0f,-0.9979f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [-0.9979f,0f,-0.0654f,0f,0f,1f,0f,0.3372f,0.0654f,0f,-0.9979f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0.3461f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0.358f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}