# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_leafw) {transformation: [-0.9962f,0f,0.0872f,0f,0f,1f,0f,0.1406f,-0.0872f,0f,-0.9962f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leafs) {transformation: [-0.9962f,0f,0.0872f,0f,0f,1f,0f,0.1406f,-0.0872f,0f,-0.9962f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leafn) {transformation: [-0.9962f,0f,0.0872f,0f,0f,1f,0f,0.1406f,-0.0872f,0f,-0.9962f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leafe) {transformation: [-0.9962f,0f,0.0872f,0f,0f,1f,0f,0.1406f,-0.0872f,0f,-0.9962f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_neck) {transformation: [-0.9962f,0f,0.0872f,0f,0f,1f,0f,0.0156f,-0.0872f,0f,-0.9962f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-0.9962f,0f,0.0872f,0f,0f,1f,0f,-0.2344f,-0.0872f,0f,-0.9962f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.2135f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.2254f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}