# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_leafw) {transformation: [-0.9848f,0f,0.1736f,0f,0f,1f,0f,0.2188f,-0.1736f,0f,-0.9848f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leafs) {transformation: [-0.9848f,0f,0.1736f,0f,0f,1f,0f,0.2188f,-0.1736f,0f,-0.9848f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leafn) {transformation: [-0.9848f,0f,0.1736f,0f,0f,1f,0f,0.2188f,-0.1736f,0f,-0.9848f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leafe) {transformation: [-0.9848f,0f,0.1736f,0f,0f,1f,0f,0.2188f,-0.1736f,0f,-0.9848f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_neck) {transformation: [-0.9848f,0f,0.1736f,0f,0f,1f,0f,0.0938f,-0.1736f,0f,-0.9848f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-0.9848f,0f,0.1736f,0f,0f,1f,0f,-0.1562f,-0.1736f,0f,-0.9848f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.1146f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.1383f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
execute on vehicle unless entity @s[tag=aj.transforms_only] at @s run function animated_java:wp_mandrake/animations/spawn/zzz/frames/2_root_commands