# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_leafw) {transformation: [-0.9808f,0f,-0.1951f,0f,0f,1f,0f,0.6094f,0.1951f,0f,-0.9808f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leafs) {transformation: [-0.9808f,0f,-0.1951f,0f,0f,1f,0f,0.6094f,0.1951f,0f,-0.9808f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leafn) {transformation: [-0.9808f,0f,-0.1951f,0f,0f,1f,0f,0.6094f,0.1951f,0f,-0.9808f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leafe) {transformation: [-0.9808f,0f,-0.1951f,0f,0f,1f,0f,0.6094f,0.1951f,0f,-0.9808f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_neck) {transformation: [-0.9808f,0f,-0.1951f,0f,0f,1f,0f,0.4844f,0.1951f,0f,-0.9808f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-0.9808f,0f,-0.1951f,0f,0f,1f,0f,0.2344f,0.1951f,0f,-0.9808f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0.2613f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0.2969f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}